name: Deploy Docker Image to Server port

on:
  push:
    branches:
      - Dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

      
    - name: Build Docker Image
      run: |
        VERSION=$(date +%Y%m%d%H%M%S)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        docker build -t ${{ secrets.DOCKER_IMAGE }}:$VERSION .
       
        
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}


    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_IMAGE }}:${{ env.VERSION }}

    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.8
      with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            VERSION=${{ env.VERSION }}
            docker pull ${{ secrets.DOCKER_IMAGE }}:$VERSION
            docker stop my-app-$VERSION  true && docker rm my-app-$VERSION  true
            docker run -d --name my-app-$VERSION -p 4321:3000 ${{ secrets.DOCKER_IMAGE }}:$VERSION